### PR TITLE
New state exp

### PR DESCRIPTION
**Pull request by scabbiaza**

### CODE REVIEW

**Comment by scabbiaza** [comment]
The main purposes of changes:
* Add ability to have different types of lists for same дата types with different filters, sorts etc.
* Unify actions.


In order to add `NewRobots` component in old architecture we could add `newRobots` cursor, similar to `robots`, with similar structure and actions.

Like so:
* call robots load data action with `filters={}, sort={id: asc} & pagination [0, 5]`
* get from API list of robots objects: `[1: {}, 2: {}, 3: {}, 4: {}, 5: {}]`

* call new robots load data action with `filters={createdOn == today}, sort={createdOn: desc} & pagination [0, Infinity]`
* get from API list of robots objects: `[5: {}, 4: {}]`

**Problems**
* storing same data types in different lists creates data duplication:
  robots with ids 4 and 5 could be out of sync after some time

* although robots 4 and 5 were already requested in Robots component, we will do another request to get the same data for NewRobots component

In order to solve this problem we will separate Data and User Interface.

We will add `DB.robots` cursor to store all requested robots, and
two cursors for our components: `UI.robots` & `UI.newRobots` with information about filters, sorts and pagination.

And in order to get data we will map DB cursor with UI cursor.

Let's look on it step by step:

* call robots load data action by `UI.robots`
  `filters={}, sort={id: asc} & pagination [0, 5]`

* get from API list of robots objects: `[1: {}, 2: {}, 3: {}, 4: {}, 5: {}] `-> put them to `DB.robots`

* to get data for list of robots we will map c with DB.robots 
  and get: `[1: {}, 2: {}, 3: {}, 4: {}, 5: {}] `

* call new robots load data action by `UI.newRobots `
  `filters={createdOn == today}, sort={createdOn: desc} & pagination [0, Infinity]`

* get from API list of robots objects: `[5: {}, 4: {}] `-> update them to `DB.robots`

* to get data for list of new robots we will map `UI.newRobots` with data in `DB.robots`
  and get: `[5: {}, 4: {}]`

So far duplication problem is solved.

What about cashing data? We could not send request to get `newRobots`, if we would know, 
that `DB.robots` has already ALL data. But we don't know it and at this moment i don't know how to do it.


Can we have one `UI.robots` for both components?
Definitely no if they are on the same screen.
(and who can guarantee that they will not be on the same screen one day?)

Maybe, if they are on different pages.
But if you will use the same cursor, by switching between pages `UI.pagination` (or in new architecture `UI.ids`) will be reset and you have to do API request for getting data again.

**Summary**: better use different cursors for different data compositions.



Next problem was very similar actions that will be growing as amount of components is growing.

https://github.com/Paqmind/react-ultimate/blob/5d83f5d33b635372d7f4b43cc776bed68541e207/frontend/actions/load-index/monster.js
https://github.com/Paqmind/react-ultimate/blob/5d83f5d33b635372d7f4b43cc776bed68541e207/frontend/actions/load-index/robot.js

And they were different by next reasons:
* they worked with different cursors and Data Types
* their UI were updated from different resources: URL for robots and inner state for monsters

I've decided to put cursors and data types as input variables and move functionality with updating cursor in separate file.

So now we have ONE action for all components:
https://github.com/Paqmind/react-ultimate/blob/25f02db4519822f8e0381b4681ce67396f4d4a39/frontend/actions/load-index/index.js

And one updateUI function (previously that code was in several places: `establishIndex` and directly in components):
https://github.com/Paqmind/react-ultimate/blob/25f02db4519822f8e0381b4681ce67396f4d4a39/frontend/actions/load-index/update-ui.js


Once actions are unified, let's look how components should work with them

BEFORE

https://github.com/Paqmind/react-ultimate/blob/5d83f5d33b635372d7f4b43cc776bed68541e207/frontend/components/index/robot.js
https://github.com/Paqmind/react-ultimate/blob/5d83f5d33b635372d7f4b43cc776bed68541e207/frontend/components/index/monster.js


First we see that loading data in components is different but it's not very explicit (for me `establishIndex` was a mystery):

Robot loading data:
`actions.establishIndex (to update UI) -> loadIndex -> fetchIndex`

Moster loading data:
`loadIndex -> fetchIndex`


Now loading data function is bigger, but you can see what is going on here:
https://github.com/Paqmind/react-ultimate/blob/25f02db4519822f8e0381b4681ce67396f4d4a39/frontend/components/index/robot.js

* update UI from URL and call `loadIndex` function.
* if offset is not correct, redirect to page with proper offset

```js
loadData: function() {
    let urlQueryCursor = state.select("urlQuery");
    let urlQuery = urlQueryCursor.get();
    let newFilters = urlQuery.filters;
    let newSorts = urlQuery.sorts;
    let newOffset = urlQuery.offset;
    let newLimit = urlQuery.limit;

    actions.updateUI(UICursor, ROBOT, {newFilters, newSorts, newOffset, newLimit});

    return new Promise((resolve, reject) => {
      resolve(actions.loadIndex(DBCursor, UICursor, Robot, api));
    }).then(() => {
      let {total, offset, limit} = UICursor.get();
      if (total) {
        let recommendedOffset = recommendOffset(total, offset, limit);
        if (offset > recommendedOffset) {
          indexRouter.transitionTo(undefined, {offset: recommendedOffset});
        }
      }
    });
  }
```



https://github.com/Paqmind/react-ultimate/blob/25f02db4519822f8e0381b4681ce67396f4d4a39/frontend/components/index/monster.js

* call` loadIndex` function
* if offset is not correct, update it to correct one

```js
loadData: function() {
    return new Promise((resolve, reject) => {
      resolve(actions.loadIndex(DBCursor, UICursor, Monster, api));
    }).then(() => {
      let {total, offset, limit} = UICursor.get();
      if (total) {
        let recommendedOffset = recommendOffset(total, offset, limit);
        if (offset > recommendedOffset) {
          actions.updateUI(UICursor, MONSTER, {newOffset: recommendedOffset});
        }
      }
    });
  }
```


Because only component knows from what its UI depends, this functionality should be inside it.
On PTF we have a case when part of UI.filters depends from URL and part are internally.  :scream_cat: 

Also notice here, that because we moved updateUI functionality to specific file, components now are much clearer.
Compare `setFilters` in monsters:

BEFORE

```js
setFilters(filters) {
    if (!equals(filters, dataCursor.get("filters"))) {
      dataCursor.set("filters", filters);
      if ((dataCursor.get("pagination").length < dataCursor.get("total")) || true) {
        /* TODO replace true with __newFilters_are_not_subset_of_oldFilters__ */
        // not all data loaded or new filters aren't subset of old
        dataCursor.merge({
          total: 0,
          pagination: [],
        });
      }
    }
    actions.loadIndex();
  }
```

 NOW
```js
 setFilters(filters) {
  actions.updateUI(UICursor, MONSTER, {newFilters: filters});
  actions.loadIndex(DBCursor, UICursor, Monster, api);
 }
```

**Comment by ivan-kleshnin** [comment]
Many cool thins :+1: 

Let's discuss decisions I'm not sure about:

```js
{ 
  UI: {
    robots: {...},
    // vs
    robot: {...}
  }
}
```

What this separation gives? Why not 

```js
{ 
  UI: {
    robots: {...}, // merge robot: {...} up here
  }
}
```

for more symmetry with `DB` part?

**Comment by ivan-kleshnin** [comment]
This is confusing:

```js
let getCurrentItems = function (DB, UI) { // <-- this is not DB, this is DB.robots / DB.monsters
  ...
};

let getCurrentItem = function (DB, UI) { // <-- this is not DB, this is DB.robot / DB.monster
  ...
};
```

**Comment by ivan-kleshnin** [comment]
Remaining things:

1. Fixes for comments
2. Filters
3. Delete
4. Try to remove Total

**Comment by ivan-kleshnin** [comment]
Questions:

`havePendingRequests` is closer to data than UI. It's only used in UI...

**Comment by scabbiaza** [comment]
Hi!

Pls watch my latest commits:
https://github.com/Paqmind/react-ultimate/commits/new-state-exp

Done:
1. Removed total
2. Refactor actions, added new remove action
3. Add cursors sync up after any data changes (see commit messages)


Still todo:
havePendingRequests is closer to data than UI. It's only used in UI...
Circular dependencies


Answering on your q

> What this separation gives? Why not

```js
{ 
  UI: {
    robots: {...}, // merge robot: {...} up here
  }
}
```

Why `robot` should be in this list? why not in any other?
I don't think can be any default list, that is why it's out, in separate cursor.

**Comment by scabbiaza** [comment]
@ivan-kleshnin, could you pls fix API tests, i didn't change anything and not sure why they failed.

**Comment by ivan-kleshnin** [comment]
I'm afraid this is going into wrong direction :disappointed: 
Cursors turned out to be a mess.
We should extract good ideas from here and start the whole state refactoring from scratch.

**Pull request closed without merging**
